[project]
name = "raglog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "DevNishantHub", email = "nishantkumar211106@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "qdrant-client>=1.19.0",
    "tenacity>=9.1.4",
]

[project.scripts]
raglog = "raglog:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
